-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: trailing-whitespace
    -   id: check-byte-order-marker
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: 7974644923f4d7cb08efd5410a1b6f3d3a6cb2b5
    hooks:
    -   id: eslint
-   repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    sha: 67c9ecc7ffee0feb391b7ff921e340d014533a15
    hooks:
    -   id: erb-validate
        args:
        - --fail-on-warnings
-   repo: https://github.com/jordant/rubocop-pre-commit-hook.git
    sha: ae431551f703fff928bfabe2b440a9a8048e962b
    hooks:
    -   id: check-rubocop
